#!/usr/bin/env ruby
require 'rubygems'
require 'bundler'
Bundler.setup
require 'hornetseye_v4l2'
require 'hornetseye_xorg'

include Hornetseye

puts "Setting up Xbox camera"

xbox_camera = V4L2Input.new '/dev/video1' do |modes|
  modes[ 1 ]
end

Thread.new do
  X11Display.show { xbox_camera.read }
end

puts "Setting up HD camera"

hd_camera = V4L2Input.new '/dev/video0' do |modes|
  modes[ 3 ]
end

Thread.new do
  X11Display.show { hd_camera.read }
end


STDIN.gets
